# action.yml
name: 'Robowoofy'
description: 'Robowoofy'
inputs:
  file:
    required: true
    description: file
  network:
    required: true
    description: network
  fn:
    required: true
    description: fn
outputs:
  nonce: # id of output
    description: ''
  safe_link:
    description: ''
  error-reason:
    description: ''
  brownie-exit-code:
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.fn }}
    - ${{ inputs.network }}